version: '3.8'

services:
  ynab-http-server:
    build: 
      context: .
      dockerfile: Dockerfile.http-server
    command: ["node", "servers/ynab-http-server/index.js"]
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - YNAB_MCP_PORT=3001
    env_file:
      - .env
    volumes:
      - ./logs:/opt/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ynab-network

  merchant-http-server:
    build: 
      context: .
      dockerfile: Dockerfile.http-server
    command: ["node", "servers/merchant-http-server/index.js"]
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - MERCHANT_MCP_PORT=3002
      - DATABASE_PATH=/opt/data/merchant_data.db
    env_file:
      - .env
    volumes:
      - ./data:/opt/data
      - ./logs:/opt/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ynab-network

  telegram-http-server:
    build: 
      context: .
      dockerfile: Dockerfile.http-server
    command: ["node", "servers/telegram-http-server/index.js"]
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - TELEGRAM_MCP_PORT=3003
    env_file:
      - .env
    volumes:
      - ./logs:/opt/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ynab-network

networks:
  ynab-network:
    driver: bridge

volumes:
  merchant-data:
  logs: